version: '2.1'

services:

  mail:
    image: ${IMAGE}${IMAGE_VER}
    restart: always
    hostname: ${APP_HOST}
    domainname: ${APP_DOMAIN}
    container_name: ${APP_HOST}
    labels:
      - "dcape.traefik.tag=${DCAPE_TAG}"
      - "traefik.enable=true"
      - "traefik.http.routers.mail.rule=Host(`${APP_SITE:?Must be set}`)"
      - "traefik.port=587"
      - "traefik.http.routers.mail.tls=true"
      - "traefik.http.routers.mail.tls.certresolver=letsEncrypt"
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "4190:4190"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${APP_ROOT}/data:/var/mail
      - ${APP_ROOT}/state:/var/mail-state
      - ${APP_ROOT}/postgrey:/etc/postgrey
      - ${APP_ROOT}/config:/tmp/docker-mailserver
      - ${APP_ROOT}/log:/var/log/mail
      - ${DCAPE_ROOT}/traefik/acme.json:/etc/letsencrypt/acme.json:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ENABLE_MANAGESIEVE=1
      - ONE_DIR=1
      - DMS_DEBUG=1
      - POSTSCREEN_ACTION=enforce
      - REPORT_RECIPIENT=1
      - REPORT_INTERVAL=daily
      - SPOOF_PROTECTION=1
      - SSL_TYPE=${SSL_TYPE} # required env values, enable SSL on the mailserver
      - SSL_CERT_PATH=/var/mail-state/manual-ssl/cert
      - SSL_KEY_PATH=/var/mail-state/manual-ssl/key
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    networks:
      - web


networks:
  web:
    external:
      name: ${DCAPE_NET}
