version: '2.1'

services:

  app:
    labels:
      - "traefik.http.services.${APP_TAG}.loadbalancer.server.port=587"
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "4190:4190"
    volumes:
      - ${APP_ROOT}/data:/var/mail
      - ${APP_ROOT}/state:/var/mail-state
      - ${APP_ROOT}/postgrey:/etc/postgrey
      - ${APP_ROOT}/config:/tmp/docker-mailserver
      - ${APP_ROOT}/log:/var/log/mail
      - ${DCAPE_ROOT}/var/traefik/acme.json:/etc/letsencrypt/acme.json:ro
    environment:
      - OVERRIDE_HOSTNAME=${APP_SITE}
      - POSTFIX_MESSAGE_SIZE_LIMIT
      - RELAY_HOST
      - RELAY_PASSWORD
      - RELAY_PORT
      - RELAY_USER
      - SSL_TYPE # required env values, enable SSL on the mailserver

      - DMS_DEBUG=1
      - ENABLE_AMAVIS=0
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=1
      - ENABLE_MANAGESIEVE=1
      - ENABLE_OPENDKIM=0
      - ENABLE_OPENDMARC=0
      - ENABLE_POLICYD_SPF=0
      - ENABLE_POP3=0
      - ENABLE_POSTGREY=0
      - ENABLE_RSPAMD=1
      - ENABLE_RSPAMD_REDIS=1
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_SPAMASSASSIN_KAM=1
      - LOGWATCH_INTERVAL=daily
      - MOVE_SPAM_TO_JUNK=1
      - ONE_DIR=1
      - PFLOGSUMM_TRIGGER=daily_cron
      - POSTSCREEN_ACTION=enforce
      - REPORT_INTERVAL=daily
      - RSPAMD_GREYLISTING=1
      - SA_SPAM_SUBJECT=***SPAM(_SCORE_)***
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - SPOOF_PROTECTION=1
      - SSL_CERT_PATH=/var/mail-state/manual-ssl/cert
      - SSL_KEY_PATH=/var/mail-state/manual-ssl/key
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
