version: '2.1'

services:

  mail:
    image: ${IMAGE}:${IMAGE_VER}
    restart: always
    hostname: ${APP_SITE}
    domainname: ${APP_DOMAIN}
    container_name: ${APP_SITE}
    labels:
      - "dcape.traefik.tag=${DCAPE_TAG}"
      - "traefik.enable=true"
      - "traefik.http.routers.mail.rule=Host(`${APP_SITE:?Must be set}`)"
      - "traefik.port=587"
      - "traefik.http.routers.mail.tls=true"
      - "traefik.http.routers.mail.tls.certresolver=letsEncrypt"
    ports:
      - "${SMTP_LISTEN}:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "4190:4190"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_PATH}/data:/var/mail
      - ${DATA_PATH}/state:/var/mail-state
      - ${DATA_PATH}/postgrey:/etc/postgrey
      - ${DATA_PATH}/config:/tmp/docker-mailserver
      - ${DATA_PATH}/log:/var/log/mail
      - ${DCAPE_ROOT}/traefik/acme.json:/etc/letsencrypt/acme.json:ro
    environment:
      - ENABLE_CLAMAV
      - POSTFIX_MESSAGE_SIZE_LIMIT
      - SSL_TYPE # required env values, enable SSL on the mailserver
      - DMS_DEBUG=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_MANAGESIEVE=1
      - ENABLE_POSTGREY=1
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_SPAMASSASSIN_KAM=1
      - ENABLE_UPDATE_CHECK=0 # wait for https://github.com/docker-mailserver/docker-mailserver/issues/2952
      - LOGWATCH_INTERVAL=daily
      - MOVE_SPAM_TO_JUNK=1
      - ONE_DIR=1
      - PFLOGSUMM_TRIGGER=daily_cron
      - POSTSCREEN_ACTION=enforce
      - REPORT_INTERVAL=daily
      - SA_SPAM_SUBJECT=***SPAM(_SCORE_)***
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - SPOOF_PROTECTION=1
      - SSL_CERT_PATH=/var/mail-state/manual-ssl/cert
      - SSL_KEY_PATH=/var/mail-state/manual-ssl/key
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    networks:
      - web

networks:
  web:
    external:
      name: ${DCAPE_NET}
