version: '2.1'

services:
  mail:
    image: ${IMAGE}:${IMAGE_VER}
    restart: always
    hostname: ${APP_HOST}
    domainname: ${APP_SITE}
    container_name: mail
    labels:
      - "traefik.enable=true"
      - "traefik.port=587"
      - "traefik.frontend.rule=Host:${APP_HOST}.${APP_SITE}"
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "4190:4190"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ../../data/mail/data:/var/mail
      - ../../data/mail/state:/var/mail-state
      - ../../data/mail/config:/tmp/docker-mailserver
      - ../../data/mail/certs:/certs
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ENABLE_MANAGESIEVE=1
      - ONE_DIR=1
      - DMS_DEBUG=1
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/certs/certs/${APP_HOST}.${APP_SITE}.crt
      - SSL_KEY_PATH=/certs/private/${APP_HOST}.${APP_SITE}.key
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

