# app custom Makefile

# Docker repo & image name without version
IMAGE    ?= ghcr.io/docker-mailserver/docker-mailserver

# Site domain
APP_DOMAIN         ?= dev.lan
# Site host
APP_HOST           ?= mail
# Site fqdn
APP_SITE           ?= $(APP_HOST).$(APP_DOMAIN)

# App names (db/user name etc)
APP_NAME ?= mail

# Do not add common docker-compose.yml
DCAPE_DC_USED = false

# ------------------------------------------------------------------------------
# app custom config

IMAGE_VER       ?= 11.3.1

# External SMTP port
SMTP_LISTEN        ?= 25
# Use ClamAV
ENABLE_CLAMAV      ?= 0
# Max essage size
POSTFIX_MESSAGE_SIZE_LIMIT ?= 52428800

# SSL type
#empty => SSL disabled
#letsencrypt => Enables Let's Encrypt certificates
SSL_TYPE           ?= letsencrypt

DCAPE_ROOT      ?= /opt/dcape/var

DATA_PATH        ?= $(DCAPE_ROOT)/$(APP_NAME)

# ------------------------------------------------------------------------------
# .env template (custom part)
# inserted in .env.sample via 'make config'
define CONFIG_CUSTOM
# ------------------------------------------------------------------------------
# app custom config, generated by make config

APP_DOMAIN=$(APP_DOMAIN)

# SSL type
#empty => SSL disabled
#letsencrypt => Enables Let's Encrypt certificates
SSL_TYPE=$(SSL_TYPE)

SMTP_LISTEN=$(SMTP_LISTEN)
ENABLE_CLAMAV=$(ENABLE_CLAMAV)
POSTFIX_MESSAGE_SIZE_LIMIT=$(POSTFIX_MESSAGE_SIZE_LIMIT)

# Path to /opt/dcape/var. Used only outside drone
DCAPE_ROOT=$(DCAPE_ROOT)

DATA_PATH=$(DATA_PATH)

endef

# ------------------------------------------------------------------------------
# Find and include DCAPE/apps/drone/dcape-app/Makefile
DCAPE_COMPOSE   ?= dcape-compose
DCAPE_MAKEFILE  ?= $(shell docker inspect -f "{{.Config.Labels.dcape_app_makefile}}" $(DCAPE_COMPOSE))
ifeq ($(shell test -e $(DCAPE_MAKEFILE) && echo -n yes),yes)
  include $(DCAPE_MAKEFILE)
else
  include /opt/dcape-app/Makefile
endif

user-add:
	docker run --rm \
	  -e MAIL_USER=$(USER_EMAIL) \
	  -e MAIL_PASS=$(USER_PASS) \
	  -ti $$IMAGE:$$IMAGE_VER \
	  /bin/sh -c 'echo "$$MAIL_USER|$$(doveadm pw -s SHA512-CRYPT -u $$MAIL_USER -p $$MAIL_PASS)"' >> $(DATA_PATH)/config/postfix-accounts.cf

# ------------------------------------------------------------------------------

dkim-add:
	docker run --rm \
	  -v $(DATA_PATH)/config:/tmp/docker-mailserver \
	  -ti $$IMAGE:$$IMAGE_VER generate-dkim-config

## make ban IP=1.1.1.1.1[/24] [BAN_APP=postfix]
ban:
	docker exec $(APP_SITE) setup fail2ban ban "$(IP)"

BAN_APP ?= custom

## make app-ban IP=1.1.1.1.1[/24] [BAN_APP=postfix]
app-ban:
	docker exec $(APP_SITE) fail2ban-client set $(BAN_APP) banip "$(IP)"

## make app-unban IP=1.1.1.1.1[/24] [BAN_APP=postfix]
app-unban:
	docker exec $(APP_SITE) fail2ban-client set $APP unbanip "$(IP)"
